In [20]:
import networkx as nx
import pandas as pd

In [21]:
#read facebook dataset
#edge file
edges_list_df=pd.read_csv('musae_facebook_edges.csv')
node_attributes=pd.read_csv('musae_facebook_target.csv')

In [62]:
edges_list_df

         id_1   id_2
0           0  18427
1           1  21708
2           1  22208
3           1  22171
4           1   6829
5           1  16590
6           1  20135
7           1   8894
8           1  15785
9           1  10281
10          1  22265
11          1   7136
12          1  22405
13          1  10379
14          1  13737
15          1   8533
16          1  14344
17          1   2812
18          1   5755
19          1  16260
20          1  15026
21          1  17370
22          1  17460
23          1   8049
24          1   5307
25          1   4987
26          1  18304
27          1  12305
28          1  19743
29          1  20024
...       ...    ...
170972  22110  22414
170973  22110  22218
170974  22110  20857
170975  22160  22253
170976  22162  22284
170977  22164  22329
170978  22166  22230
170979  22166  22280
170980  22166  22228
170981  22181  22354
170982  22187  22239
170983  22222  22305
170984  22224  22375
170985  22228  22230
170986  22242  22403
170987  22242  22261
170988  22261  22403
170989  22261  21546
170990  21439  22338
170991  22294  22303
170992  22294  22329
170993  22305   3832
170994  21546  22403
170995  22316   8302
170996  22329  22440
170997  20188  20188
170998  22340  22383
170999  22348  22348
171000   5563   5563
171001  22425  22425

[171002 rows x 2 columns]

In [22]:
node_attributes

,id,facebook_id,page_name,page_type
0,0,145647315578475,The Voice of China ä¸­å›½å¥½å£°éŸ³,tvshow
1,1,191483281412,U.S. Consulate General Mumbai,government
2,2,144761358898518,ESET,company
3,3,568700043198473,Consulate General of Switzerland in Montreal,government
4,4,1408935539376139,Mark Bailey MP - Labor for Miller,politician
5,5,134464673284112,Victor Dominello MP,politician
6,6,282657255260177,Jean-Claude Poissant,politician
7,7,239338246176789,Deputado Ademir Camilo,politician
8,8,544818128942324,T.C. Mezar-Ä± Åžerif BaÅŸkonsolosluÄŸu,government
9,9,285155655705,Army ROTC Fighting Saints Battalion,government
10,10,295294787190810,NASA Student Launch,government
11,11,837707072929819,Eliziane Gama,politician
12,12,189778427932,Socialstyrelsen,government
13,13,153345494745119,Brisbane Water LAC - NSW Police Force,government
14,14,374623305761,NASA's Marshall Space Flight Center,government
15,15,135948233146402,Municipio de Lomas de Zamora,government
16,16,218961468129322,Die Techniker (TK),company
17,17,603089303044139,Digvijaya Singh,politician
18,18,107219255341,1st Armored Division Sustainment Brigade,government
19,19,288891469878,Shapeways,company
20,20,200750393327673,FranÃ§oise GuÃ©got,politician
21,21,312378712151391,Hydro Coco,company
22,22,197257747038268,Embassy of the Netherlands in Uganda,government
23,23,121925517901889,Ford Danmark,company
24,24,127122004049986,Schweppes Australia,company
25,25,9615015947,TalkTalk,company
26,26,136577286212,National Institute of General Medical Sciences,government
27,27,220206968012871,Poppy Cat,tvshow
28,28,77064798220,Tahiti Tourisme,company
29,29,314467271901260,Marriott Rewards,company
...,...,...,...,...
22440,22440,178004959035323,City of Los Altos Police Department,government
22441,22441,681337358647228,Greg Hands,politician
22442,22442,125592660803518,Abarth,company
22443,22443,121219973056,EnergySaver.gov,government
22444,22444,171920102858673,Jerome Mika,politician
22445,22445,129948247195586,Bill Johnston MLA,politician
22446,22446,10150125867040707,Triumph,company
22447,22447,216131338502087,GIORDANO,company
22448,22448,247550775394251,Marietje In Europa,politician
22449,22449,117253284954062,U.S. Army 261st Multifunctional Medical Battalion,government
22450,22450,109959002750968,Cr Amanda Cooper,politician
22451,22451,633018823475154,Professor Yemi Osinbajo,politician
22452,22452,325334034153429,Uwaga! po Uwadze,tvshow
22453,22453,505317482889209,Maria Elena Boschi,politician
22454,22454,1544292215816153,Premier Boxing Champions,tvshow
22455,22455,149100528467930,Monroe County Sheriff's Office,government
22456,22456,1770412783239131,NYPD 33rd Precinct,government
22457,22457,53724708836,OLTURSA,company
22458,22458,475061202627239,Nicholas Sarwark,politician
22459,22459,543519302451197,Pizzaro,company
22460,22460,208741279137778,US National Weather Service Amarillo Texas,government
22461,22461,238809486131187,Bosch Professional Power Tools and Accessories,company
22462,22462,562512487251956,Werner Langen,politician
22463,22463,170298223273,Memphis VA Medical Center,government
22464,22464,198333355974,Keurig,company
22465,22465,1379955382222841,Kurt Wiegel MdL,politician
22466,22466,1651527995097082,dubdub Stories,company
22467,22467,155369444540412,Ministerio del Interior - Paraguay,government
22468,22468,175067819212798,Tottus PerÃº,company
22469,22469,27208897877,SPORT1 Doppelpass,tvshow

In [23]:
G = nx.Graph()

In [26]:
 G.add_edges_from(edges_list_df.values.tolist())

In [27]:
G

In [30]:
len(G)

22470

In [32]:
print(nx.info(G))

Name:
Type: Graph
Number of nodes: 22470
Number of edges: 171002
Average degree:  15.2205

In [50]:
node_dict=node_attributes.to_dict('index')

In [53]:
nx.set_node_attributes(G,node_dict)

In [57]:
G.nodes[0]['page_type']

'tvshow'

In [56]:
nx.write_gexf(G,'facebook.gexf')

In [60]:
largest_component=max(nx.connected_component_subgraphs(G), key=len)

In [61]:
print(nx.info(largest_component))

Name:
Type: Graph
Number of nodes: 22470
Number of edges: 171002
Average degree:  15.2205